### PR TITLE
Use the AFELD.ME proxy instead of karantza.

### PR DESCRIPTION
**Pull request by Ganon11**
At least if the proxy dies, we'll be killing some other service instead of karantza.org

### CODE REVIEW

**Comment by adinaelisheva** [comment]
did you find this via that forum thread or...?

**Comment by Ganon11** [comment]
Yeah, it was one of the replies here: http://community.extra-life.org/forums/topic/1940-jsonp-or-cors-support/

Actual page here: https://jsonp.afeld.me/

**Comment by adinaelisheva** [comment]
I don't fully understand the whole JSON/JSONP distinction ... will this affect the data we get back from our calls? if not then :+1:  :ship: :it:

**Comment by Ganon11** [comment]
AFAICT, it shouldn't, although I guess I should... y'know, test it.

**Comment by adinaelisheva** [comment]
&gt;_>

**Comment by Ganon11** [comment]
Tested it; it works (and really fast) after escape()ing the requested URL.

**Pull request merged**
